services:
  mongo:
    build: ./mongo
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb
  neo4j:
    build:
      context: ./neo4j
      args:
        NEO4J_IMAGE: ${NEO4J_IMAGE:-neo4j:4.3.7}
    ports:
      - ${NEO4J_PORT_HTTP:-7474}:7474
      - ${NEO4J_PORT_BOLT:-7687}:7687
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_PORT_HTTP=${NEO4J_PORT_HTTP:-7474}
      - NEO4J_PORT_BOLT=${NEO4J_PORT_BOLT:-7687}
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-conf:/conf
      - neo4j-var:/var/lib/neo4j
      - neo4j-plugins:/plugins
      - neo4j-cyphers:/cyphers
volumes:
  mongo-db:
  mongo-configdb:
  neo4j-data:
  neo4j-logs:
  neo4j-conf:
  neo4j-var:
  neo4j-plugins:
  neo4j-cyphers:
