services:
  mongo-test:
    container_name: mongo-test
    build: ./mongo
    restart: always
    ports:
      - ${MONGO_PORT_TEST:-27018}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
  neo4j-test:
    container_name: neo4j-test
    build:
      context: ./neo4j
      args:
        NEO4J_IMAGE: ${NEO4J_IMAGE:-neo4j:4.3.7}
    restart: always
    ports:
      - ${NEO4J_PORT_HTTP_TEST:-7475}:7474
      - ${NEO4J_PORT_BOLT_TEST:-7688}:7687
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
